- .travis.yml
They boot faster and since we don't use sudo we can use them.
> Use travis' new build workers

- README.rst
When I first started looking into this package I initially found it difficult to find the user oriented documentation. Right now, a link to the docs are not displayed on the github page, nor the PyPI page. This will hopefully make it simpler for other users.
> Display link to documentation in README.

- chardet/__init__.py
- chardet/compat.py
First, it is wrong: ValueError is about bad value of the right type,
but the error and the check is about type, not value.
Second, it lies about argument type assuming it unicode for all the
cases that are not valid. What gives you happy debug times until you
finally open chardet source code.
Third, chardet need to respect bytearray type as it could work with it
fine and which one is a legit for holding binary strings in PY3.
> Fix chardet.detect exception

- docs/faq.rst
Feedparser urls were broken in documentation, as it had moved from independent hosting at http://feedparser.org/ to https://pythonhosted.org/feedparser/. The documentation linked was a very helpful guide to [following XML standards before doing character detection](https://pythonhosted.org/feedparser/character-encoding.html). 
Please let me know if there's anything else I need to do for a pull request to `chardet` and thanks for the great package!
> Updating Feedparser URLs

- .travis.yml
- setup.py
- test.py
The concept here is pretty simple: This tries to test for the
invariant that if a string comes from valid unicode and is
encoded in one of the chardet supported encodings then chardet
should detect *some* encoding.
More nuanced tests are possible (e.g. asserting that the string
should be decodable from the detected encoding) but given
that even this test is demonstrating a bunch of bugs this seemed to
be a good starting point.
This is (more or less) the test that caught #65, #64 and #63. #62 had one extra line in it to try to reencode the data as the reported format. 
Notes:
1. This test is currently failing. I'm pretty sure this is because of issues it's finding in the code, not issues with the test.
2. min_size=100 is to rule out bugs that come solely from the length, prompted by your …
> Add Hypothesis based test of chardet

- README.rst
- docs/how-it-works.rst
- docs/supported-encodings.rst
I also changed a derogatory reference to middle managers to a more
useful explanation Windows 1252/ISO-8859-1.
> Note that ISO-8859-1 is equivalent (for chardet) to Windows 1252

- docs/faq.rst
The linked article was moved to the Mozilla archive.
> Fixed broken link.

- chardet/latin1prober.py
- chardet/universaldetector.py
This fixes some mixups where we would report ISO encodings even when we saw bytes in the `\x80-\x9F` range.
This was pulled out of #99 to make that PR smaller.
> Report back Windows encodings only when we have evidence

- chardet/cli/chardetect.py
This should be a useful performance improvement.   I've got some 100MB files and they take quite a few seconds to read through from my local SSD - and imagine if someone was reading across the network.
If the unicode byte-order mark is read in the first line of the file, it really makes no sense to read the rest of the file off disk.
I fixed the unit tests in the previous PR because I wanted to assure myself this introduced no regression (it appears not to.)
cheers
> stop reading file immediately when filetype known

- chardet/__init__.py
- chardet/chardistribution.py
- chardet/cli/chardetect.py
- chardet/codingstatemachine.py
- chardet/compat.py
- chardet/escprober.py
- chardet/hebrewprober.py
- chardet/jpcntx.py
- chardet/latin1prober.py
- chardet/sbcharsetprober.py
- chardet/universaldetector.py
We now process `bytearray` objects all over the place, which greatly simplifies compatibility between Python 2 and 3, as both treat `bytearray` objects the same (as mutable lists of integers).
> Switch from wrap_ord to bytearray

- MANIFEST.in
This makes it possible to run tests using the source tarball that is hosted on PyPI.
> MANIFEST.in: include test.py

- chardet/universaldetector.py
- chardet/version.py
Will merge this into `stable` to get a 3.0.3 release that stops this crash. Holding off on just releasing what we have in `master` because it has some non-backward compatible API changes and will require a major version number change, which I want to hold off until we have good retrained models.
> Hotfix: Fix crash when debug logging is enabled and passed empty string

- README.rst
- docs/README.md
Projects should now use readthedocs.io instead of readthedocs.org. Fixed links to use https.
> Prefer readthedocs.io over readthedocs.org

- chardet/__init__.py
- chardet/universaldetector.py
- test.py
As discussed in #96, here's my solution for the encodings listing problem.
For info, this was my first  version: Just adding a method `detect_all` to `__init__.py`:
```python
def detect_all(byte_str):
if not isinstance(byte_str, _bin_type):
raise TypeError('Expected object of {0} type, got: {1}'
''.format(_bin_type, type(byte_str)))
u = UniversalDetector()
u.feed(byte_str)
u.close()
results = [
{
'encoding': prober.charset_name,
'confidence': prober.get_confidence()
} for prober in u._charset_probers
if prober.get_confidence() > u.MINIMUM_THRESHOLD
]
return sorted(results, key=lambda r: -r['confidence'])
```
> Add API option to get all the encodings confidence #96

- .travis.yml
- README.rst
- bench.py
- setup.py
- test.py
Python 2.6 and 3.3 is EOL and is no longer receiving bug fixes, including security fixes.
https://snarky.ca/stop-using-python-2-6/
http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html
Fixes #133
> Drop support for Python 2.6

- test.py
Fixes https://github.com/chardet/chardet/issues/173
> Support pytest 4, don't apply marks directly to parameters

- .travis.yml
- setup.py
- test.py
Use Xenial on Travis to allow Python 3.7. Document that PyPy is also
supported.
>  Test Python 3.7 and 3.8 and document support

- setup.py
There is a weird bug in python 2.7 that causes a NameError when trying to install this package using `run_setup` in distutils..
https://bugs.python.org/issue23426 seams related, but does not work in this case.
Here is the error it fixes..
```
In [1]: from distutils.core import run_setup
In [2]: run_setup('setup.py', ['bdist_egg'])
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-cd35a16b7b8c> in <module>()
----> 1 run_setup('setup.py', ['bdist_egg'])
/usr/local/lib/python2.7/distutils/core.pyc in run_setup(script_name, script_args, stop_after)
216             f = open(script_name)
217             try:
--> 218                 exec f.read() in g, l
219             finally: …
```
> Workaround for distutils bug in python 2.7

- chardet/cli/chardetect.py
When packaging chardet and pip (which bundles it) in Fedora, we have realized
that there is a nonexecuatble file with a shebang line.
It seems that the primary purpose of this file is to be imported from Python
code or to be executed via `python chardet/cli/chardetect.py` or `python -m
chardet.cli.chardetect` and hence the shebang appears to be unnecessary.
Shebangs are hard to handle when doing downstream packaging, because it makes
sense for upstream to use `#!/usr/bin/env python` while in the RPM package, we
need to avoid that and use a more specific interpreter. Since the shebang was
unused, I propose to remove it to avoid the problems.
> Remove shebang from nonexecutable script

- setup.cfg
- setup.py
Since setuptools v41.5.0 (27 Oct 2019), the 'test' command is formally
deprecated and should not be used.
The pytest-runner package also lists itself as deprecated:
https://github.com/pytest-dev/pytest-runner
> Deprecation Notice
>
> pytest-runner depends on deprecated features of setuptools and relies
> on features that break security mechanisms in pip. For example
> 'setup_requires' and 'tests_require' bypass pip --require-hashes. See
> also https://github.com/pypa/setuptools/issues/1684.
> Remove use of deprecated 'setup.py test'

- chardet/__init__.py
- chardet/cli/chardetect.py
Has been unnecessary since Python 2.7.
> Remove unnecessary numeric placeholders from format strings

- chardet/cli/chardetect.py
The CLI entry point is installed by setuptools through the `console_scripts` option. This setuptools feature automatically constructs a file with a shebang and sets the executable bit. The imported file
`chardet.cli.chardetect` doesn't also require this bit.
> Remove shebang and executable bit from chardet/cli/chardetect.py

- chardet/charsetgroupprober.py
Throughout the rest of the chardet code we assume that FOUND_IT means we can stop looking. Previously the CharsetGroupProber did not set its state appropriately when a child prober returned FOUND_IT. This substantially speeds up the chardet for most encodings.
Fixes #202
Before change:
```
Benchmarking chardet 4.0.0 on CPython 3.7.5 (default, Sep  8 2020, 12:19:42)
[Clang 11.0.3 (clang-1103.0.32.62)]
--------------------------------------------------------------------------------
........................................................................................................................................................................................................................................................................................................................... …
```
> Properly set CharsetGroupProber.state to FOUND_IT

- chardet/charsetprober.py
- chardet/latin1prober.py
- chardet/sbcharsetprober.py
This should prevent us from inadvertently having a bunch of XML/HTML tags influencing detection results.
Also rename `filter_with_english_letters` to `remove_xml_tags` since that's what it actually does.
This was originally part of #99 , but I'm trying to pull out the parts that didn't break there, so that all that's left is the model retraining in #99.
> Always remove XML tags when detecting single-byte charset encodings that use ASCII letters

- chardet/sbcharsetprober.py
Likely characters count for 25% now, and too many control characters decrease confidence, just like in uchardet.
> Tweak SingleByteCharSetProber confidence

- chardet/__init__.py
Otherwise you won't actually see all the individual encodings nested inside the MBCSGroupProber and SBCSGroupProber classes.
> Make detect_all return child prober confidences

- docs/usage.rst
> Update examples in usage.rst to Python 3

- setup.cfg
Universal wheels are for code expected to work on both Python 2 and 3:
* https://wheel.readthedocs.io/en/stable/user_guide.html#building-wheels
> Don't build universal wheels

- .pre-commit-config.yaml
Fixes the warning:
[WARNING] The 'rev' field of repo 'https://github.com/ambv/black'
appears to be a mutable reference (moving tag / branch). Mutable
references are never updated after first install and are not
supported. See
https://pre-commit.com/#using-the-latest-version-for-a-repository
for more details. Hint: `pre-commit autoupdate` often fixes this.
Fixed by running the command "pre-commit autoupdate".
> Pin Black to its latest version in the .pre-commit-config.yaml file

- .github/workflows/test.yml
- setup.py
Python 3.10.0 final is due for release in October:
* https://www.python.org/dev/peps/pep-0619/
The first release candidate is now out and the Python release team has issued a call to action for community members:
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.10 compatibilities during this phase. As always, report any issues to the Python bug tracker.
https://discuss.python.org/t/python-3-10-0rc1-is-now-available/9982?u=hugovk
So let's also test and add support for 3.10.
> Add support for Python 3.10

- .pre-commit-config.yaml
- chardet/charsetprober.py
```
pytest
```
***Master:*** 367 passed, 5 xfailed, 1 xpassed in 15.24s 
***Commit:*** 367 passed, 5 xfailed, 1 xpassed in 14.73s
___
```
python3 bench.py
```
***Master:***
```
Benchmarking chardet 5.0.0dev0 on CPython 3.10.4 (main, Mar 24 2022, 13:07:27) [GCC 11.2.0]
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
Calls per second for each encoding:
ascii: 58908.76404494382
big5: 21.534473374712764
cp932: 8.165127375060932
cp949: 12.310296784615652
euc-jp: 7.129459713562277
euc-kr: 20.82451066846787
euc-tw: 145.64819862835316
gb2312: 24.251619432823837
ibm855: 56.16913800549732
ibm866: 69.08196781313022
iso-2022-jp: 5885.916362615773
iso-2022-kr: 45964.975342465754 …
```
> slight increase in performance

- setup.cfg
The [LGPLv2+ trove classifier](https://github.com/pypa/trove-classifiers/blob/3458f52f2d91eb8fc5deab40964a17c5684435db/src/trove_classifiers/__init__.py#L266) reflects the text “`version 2.1 of the License, or (at your option) any later version`” in the source file header comments.
> Clarify LGPL version in License trove classifier

- .github/workflows/test.yml
- README.rst
- setup.cfg
Python 3.6 went EOL on 2021-12-23. It is no longer receiving bug fixes,
including for security issues.
Remove the testing resources and support for EOL Pythons.
https://devguide.python.org/devcycle/#end-of-life-branches
> Remove support for EOL Python 3.6

- chardet/version.py
- pyproject.toml
- setup.py
setuptool no longer recommends using setup.py. Instead, build the
package using:
python -m build
The command builds both the sdist and wheel.
For additional information, see:
https://setuptools.pypa.io/en/latest/userguide/quickstart.html
> Remove setup.py in favor of build package

- .github/workflows/test.yml
- .pre-commit-config.yaml
- chardet/__init__.py
- chardet/cli/chardetect.py
- chardet/universaldetector.py
- test.py
This PR adds a new `should_rename_legacy` flag, so that people can opt into renaming legacy encodings according to the W3C offshoot WHATWG group's suggested mapping [here](https://encoding.spec.whatwg.org/#names-and-labels). This should address long-standing complaint about us returning `gb2312` instead of at least `gbk`, and things like that. One interesting side effect of this change is that they suggest mapping ASCII and ISO-8859-1 to Windows-1252, so we will return Windows-1252 a lot more often with this flag on.
> Add should_rename_legacy flag to allow WHATWG-inspired renaming
